"""Add share content control fields

Revision ID: 098b4cc923ab
Revises: 583c21d10357
Create Date: 2025-05-01 20:36:40.974934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098b4cc923ab'
down_revision = '583c21d10357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_exposure', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_aperture', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_favorite_film', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_gear', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_shoot_time', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_column('share_shoot_time')
        batch_op.drop_column('share_gear')
        batch_op.drop_column('share_favorite_film')
        batch_op.drop_column('share_aperture')
        batch_op.drop_column('share_exposure')

    # ### end Alembic commands ###
