"""Add share content control fields

Revision ID: fece2771ed76
Revises: 098b4cc923ab
Create Date: 2025-05-01 21:05:43.497912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fece2771ed76'
down_revision = '098b4cc923ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_share', ['from_user_id', 'to_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_share', type_='unique')

    # ### end Alembic commands ###
